---
# Location where configuration files will be stored.
config_dir: '~'

# docker-obs configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "change.me.please"

caddy_email: foo@bar.com

prombackup_repo: https://github.com/drio/prombackup
prombackup_repo_local_destination: ./docker-obs/prombackup/prombackup-repo
prombackup_repo_accept_hostkey: true

prombackup_listen_port: 8888
prombackup_s3_bucket_name: drio-prom-timeseries-snap
prombackup_s3_bucket_region: us-east-1
prombackup_prometheus_server: http://prometheus:9090
prombackup_snapdir: /data/prometheus/snapshots
prombackup_tarball_name: obstack-prom-snapshot.tar.gz
prombackup_zero_seconds: 60

ksak_listen_port: 9001
ksak_repo: https://github.com/drio/ksak
ksak_repo_local_destination: ./docker-obs/ksak/ksak-repo
ksak_repo_accept_hostkey: true
ksak_version: master
ksak_url: 'localhost:9092'
ksak_username: ''
ksak_password: ''

tls_jmx_proxy_repo: https://github.com/drio/go-tls-proxy

am_smtp_smarthost: smtp-mail.xxxx.com:587
am_smtp_from: xxxx@outlook.com
am_smtp_auth_username: xxx@outlook.com
am_smtp_auth_password: pass
am_drio_email: email_here
