---
# Location where configuration files will be stored.
config_dir: '~'

# docker-obs configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "change.me.please"

caddy_email: foo@bar.com
