---
# Location where configuration files will be stored.
config_dir: '~'

# docker-obs configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
kafka_enable: false # run kafka + zk containers
