---
- hosts: obs-machine-01
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml.tufts
      tags:
        - always

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Create data dirs for prometheus
      file:
        path: /data/prometheus
        state: directory
        # nobody
        owner: 65534
        group: 65534
        mode: 0775

    - name: Create data dirs for grafana
      file:
        path: /data/grafana
        state: directory
        owner: 472
        group: 472
        mode: 0775

    - name: Create data dirs for alertmanager
      file:
        path: /data/alertmanager
        state: directory
        # nobody
        owner: 65534
        group: 65534
        mode: 0775

    - name: Pull prombackup repo locally
      git:
        repo: "{{ prombackup_repo }}"
        dest: "{{ prombackup_repo_local_destination }}"
        accept_hostkey: "{{ prombackup_repo_accept_hostkey }}"
      become: false
      tags: [ "always" ]

    - name: Pull ksak repo locally (for test-cp)
      git:
        repo: "{{ ksak_repo }}"
        dest: ./docker-obs/test-cp/ksak-repo
        accept_hostkey: true
      become: false
      tags: [ "always" ]

    - name: Pull proxy repo locally
      git:
        repo: "{{ tls_jmx_proxy_repo }}"
        dest: ./docker-obs/tls-jmx-proxy/proxy-repo
        accept_hostkey: true
      become: false
      tags: [ "always" ]

    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Set up the observability stack (prometheus/grafana)
      ansible.builtin.import_tasks: tasks/docker-obs.yml
      when: monitoring_enable
      tags: [ "sync-docker-obs" ]

    - name: Few setup tasks for the machine
      ansible.builtin.import_tasks: tasks/machine.yml

    - name: Docker info
      ansible.builtin.import_tasks: tasks/docker-info.yml
      tags: [ "info", "dockerps", "never" ]

    - name: Docker stop
      ansible.builtin.import_tasks: tasks/docker-stop.yml
      tags: [ "dockerstop", "never" ]

    - name: Prune all docker images
      ansible.builtin.import_tasks: tasks/docker-prune.yml
      tags: [ "dockerprune", "never" ]

    - name: Full update of the OS
      ansible.builtin.import_tasks: tasks/full-update.yml
      tags: [ "fullupdate", "never" ]

    - name: Grafana related tasks
      ansible.builtin.import_tasks: tasks/grafana.yml
      tags: [ "grafana" ]
      become: false

    # Use these tasks via tags to restart services.
    # Ideal when developing
    #
    - name: Update the prombackup service
      ansible.builtin.import_tasks: tasks/prombackup.yml
      tags: [ "updateprombackup", "never" ]
      become: false

    - name: Update the test-cp service
      ansible.builtin.import_tasks: tasks/test-cp.yml
      tags: [ "updatetestcp", "never" ]
      become: false

    - name: Update the kafka service
      ansible.builtin.import_tasks: tasks/kafka.yml
      tags: [ "updatekafka", "never" ]
      become: false

    - name: Update the prometheus service
      ansible.builtin.import_tasks: tasks/prometheus.yml
      tags: [ "updateprometheus", "never" ]
      become: false
