---
- hosts: obs-machine-01
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml.tufts
      tags:
        - always

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Create data dirs for prometheus and grafana
      file:
        path: /data/prometheus
        state: directory
        # nobody
        owner: 65534
        group: 65534
        mode: 0775

    - name: Create data dirs for grafana
      file:
        path: /data/grafana
        state: directory
        owner: 472
        group: 472
        mode: 0775

    - name: Pull prombackup repo locally
      git:
        repo: "{{ prombackup_repo }}"
        dest: "{{ prombackup_repo_local_destination }}"
        accept_hostkey: "{{ prombackup_repo_accept_hostkey }}"
      become: false
      tags: [ "always" ]

    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Set up the observability stack (prometheus/grafana)
      ansible.builtin.import_tasks: tasks/docker-obs.yml
      when: monitoring_enable

    - name: Few setup tasks for the machine
      ansible.builtin.import_tasks: tasks/machine.yml

    - name: Docker info
      ansible.builtin.import_tasks: tasks/docker-info.yml
      tags: [ "info", "dockerps", "never" ]

    - name: Docker stop
      ansible.builtin.import_tasks: tasks/docker-stop.yml
      tags: [ "dockerstop", "never" ]

    - name: Prune all docker images
      ansible.builtin.import_tasks: tasks/docker-prune.yml
      tags: [ "dockerprune", "never" ]

    - name: Full update of the OS
      ansible.builtin.import_tasks: tasks/full-update.yml
      tags: [ "fullupdate", "never" ]

    - name: Update the prombackup server
      ansible.builtin.import_tasks: tasks/prombackup.yml
      tags: [ "updateprombackup", "never" ]
      become: false
