---
- name: Rebuild and restart the prombackup-server service
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker-obs/"
    restarted: yes
    build: yes
    services:
      - prombackup-server

