---
- name: Rebuild and restart the prometheus service
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker-obs/"
    restarted: yes
    build: yes
    services:
      - prometheus
